### ISSUE TITLE
[Bug]: still can not build pass on win pc

### ISSUE THREAD

**Issue by william19831103** [Sagiroth/TortoiseBots#156]
### What does this relate to?

Build or configuration

### What happened?

I updated to the latest source code and saw that Boot Helper is now supported. But after I installed your mod, the compilation failed again. It's on the Windows platform. I installed the mod in the project at E:\MaNGOS_Turtle\patch_1171\modules\TortoiseBots. Why does it show an error during compilation?

3>E:\MaNGOS_Turtle\patch_1171\modules\TortoiseBots\ai\playerbot\PlayerbotLLMInterface.cpp(16,10): error C1083: Cannot open include file: 'openssl/ssl.h': No such file or directory
3>(compiling source file '../../patch_1171/modules/TortoiseBots/ai/playerbot/PlayerbotLLMInterface.cpp')
3>SayAction.cpp
3>E:\MaNGOS_Turtle\patch_1171\modules\TortoiseBots\ai\playerbot\MemoryMonitor.cpp(8,10): error C1083: Cannot open include file: 'boost/stacktrace.hpp': No such file or directory
3>(compiling source file '../../patch_1171/modules/TortoiseBots/ai/playerbot/MemoryMonitor.cpp')

### How can we reproduce it?

I updated to the latest source code and saw that Boot Helper is now supported. But after I installed your mod, the compilation failed again. It's on the Windows platform. I installed the mod in the project at E:\MaNGOS_Turtle\patch_1171\modules\TortoiseBots. Why does it show an error during compilation?

3>E:\MaNGOS_Turtle\patch_1171\modules\TortoiseBots\ai\playerbot\PlayerbotLLMInterface.cpp(16,10): error C1083: Cannot open include file: 'openssl/ssl.h': No such file or directory
3>(compiling source file '../../patch_1171/modules/TortoiseBots/ai/playerbot/PlayerbotLLMInterface.cpp')
3>SayAction.cpp
3>E:\MaNGOS_Turtle\patch_1171\modules\TortoiseBots\ai\playerbot\MemoryMonitor.cpp(8,10): error C1083: Cannot open include file: 'boost/stacktrace.hpp': No such file or directory
3>(compiling source file '../../patch_1171/modules/TortoiseBots/ai/playerbot/MemoryMonitor.cpp')

**Comment by Sagiroth** [comment]
Hi @william19831103,

Two separate things are causing these compile errors on Windows:

1. **Core Version Mismatch:**
Your path shows you are building inside `patch_1171` (Turtle 1.17.1). `TortoiseBots` exclusively targets **Tortoise WoW 1.18.1** (`1181dev` branch on [`tortoise-wow`](https://github.com/tortoise-wow/tortoise-wow)). It will not compile on 1.17.1.

2. **Missing vcpkg Dependencies:**
On Windows, `openssl/ssl.h` and `boost/stacktrace.hpp` are provided through vcpkg. When following the documented Windows build pipeline:
- Ensure you have installed the required dependencies: `openssl:x64-windows` and `boost-stacktrace:x64-windows`.
- Configure CMake pointing to your vcpkg installation (e.g. `-DACE_ROOT=C:\path\to\vcpkg\installed\x64-windows`).

*(Note for runtime)*: Once compilation succeeds, make sure you also cherry-pick [tortoise-wow PR #496](https://github.com/tortoise-wow/tortoise-wow/pull/496) (or update once merged into `1181dev`), which ensures the OpenSSL 3 DLLs (`libcrypto-3-x64.dll`) are copied to your server install directory so `mangosd.exe` can launch without missing DLL errors.

**Comment by william19831103** [comment]
> 2\. stacktrace.hpp
Please ignore my folder patch_1171. In fact, I have already merged the patch_1171 source code with the main branch of Tortoise WoW 1.18.1. It is exactly the same as Tortoise WoW 1.18.1. Second, my local computer has Boost 1.7.4 installed. When I compile AZ Core 3.3.5, it will automatically find the environment. Can you set it up to be as foolproof to compile as AZ? The tutorial for point 2 looks a bit complicated.

**Comment by Sagiroth** [comment]
Hi @william19831103 — clarifying what fixes what, so nothing gets mixed up:

**1. tortoise-wow PR #496 will NOT fix your build errors.**

Your errors are compile-time `C1083` (missing headers: `openssl/ssl.h` in `PlayerbotLLMInterface.cpp:16`, `boost/stacktrace.hpp` in `MemoryMonitor.cpp:8`). No `.exe` exists yet at that stage.

PR #496 is runtime-only: it copies `libcrypto-3-x64.dll` / `libssl-3-x64.dll` at install time so an already-built `mangosd.exe` can launch (that fixes `STATUS_DLL_NOT_FOUND`, i.e. issue tortoise-wow#485). Taking it will not make your compilation pass — you still need the vcpkg packages (`openssl:x64-windows` + `boost-stacktrace:x64-windows`) for the Windows build.

**2. Why two OpenSSL DLL families?**

Both are really needed, not duplicates: the old linkage uses 1.1 (`libcrypto-1_1-x64.dll`, from `dep/windows`), while the login code in `ARC4.cpp` calls `OSSL_PROVIDER_load(NULL, "legacy")`, which only exists in OpenSSL 3.x — so the binary also pulls `libcrypto-3-x64.dll` from the vcpkg tree. That is why #496 adds the `-3` pair without removing the `-1_1` pair.

**3. On Boost 1.7.4 vs AZCore:**

Fair point — AZ "just finds it" because it runs Boost discovery in CMake. This project currently has no `find_package(Boost)`, and `dep/windows/include/` ships only `mysql/ openssl/ zlib/`, so a separately installed Boost is invisible to the build. Making the Windows module build as foolproof as AZ (auto-find or drop the hard dependency where the code is now stubbed/disabled) is a valid enhancement — I'll track that separately.

Closing this as `not-a-bug` since the module targets Tortoise WoW 1.18.1 plus the documented Windows deps as of today; the enhancement will reference this issue. Thanks for reporting.

**Comment by Sagiroth** [comment]
https://github.com/Sagiroth/TortoiseBots/issues/166

**Comment by Sagiroth** [comment]
Tracked as #166 (foolproof Windows build — sizing + plan in the comments there).
